version: "3.2"
services:
  php:
    build:
      context: '../'
      dockerfile: 'docker/Dockerfile'
    networks:
      - net
    volumes:
      - ${PWD}/../:/var/www/html/
    ports:
      - "80:80"
    container_name: php
  mysql:
    image: mysql:8.0.37-debian
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - net
    env_file:
      - '../.env.example'
    container_name: ${MYSQL_HOST}
networks:
  net:
volumes:
  data: